services:
  smzdm_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: enwaiax/smzdm_bot
    container_name: smzdm_bot
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    env_file:
      - .env
    # Uncomment to use config.toml for multi-user support
    # volumes:
    #   - ./config.toml:/smzdm_bot/config/config.toml
